"""
Plot two graphs generated with the two different random generation methods.
The image generated by this script is used in the main README.md.
"""
import matplotlib.pyplot as plt

from census.utils.random import generate_graph_diamond_pattern, generate_graph_random_conditional
from census.utils.graphs import build_udg
from census.utils.visualization import plot_graph, plot_bb

fig, ax = plt.subplots(1, 2, figsize=(12, 6))

seed = 3

# diamond pattern
graph_1 = generate_graph_diamond_pattern(
    x_rows=3,
    y_rows=3,
    seed=seed
)
build_udg(graph_1)

ax[0].set(title=f"Diamond pattern")
plot_graph(graph=graph_1, ax=ax[0], fig=fig, with_edges=True, with_hearing_radii=True)
plot_bb(graph=graph_1, ax=ax[0])

# random conditional
graph_2 = generate_graph_random_conditional(
    n = 13,
    pct_overlap=0.4,
    bb_limit=1.0,
    seed=seed
)
build_udg(graph_2)

ax[1].set(title=f"Overlap condition")
plot_graph(graph=graph_2, ax=ax[1], fig=fig, with_edges=True, with_hearing_radii=True)
plot_bb(graph=graph_2, ax=ax[1])

# plt.tight_layout()
# plt.show()
plt.savefig("../images/graph-generation_example_1.jpg", bbox_inches="tight")

